/*
 * TTable.h
 * Generated by gen_ttable.py
 *
 * Header file for quantiles of the Student's t-distribution
 */

#ifndef TTABLE_H_
#define TTABLE_H_

enum ALPHAS {ALPHA_0_005, ALPHA_0_00625, ALPHA_0_001, ALPHA_0_0125, ALPHA_0_025, ALPHA_0_05};

extern const int ttable_minor_count;
extern const int ttable_boost;
extern const int ttable_df_max;

extern const double ttable_icdf[6][900];

#endif /* TTABLE_H_ */
