/*
 * TTable.h
 * Generated by gen_ttable.py
 *
 * Header file for quantiles of the Student's t-distribution
 */

#ifndef TTABLE_H_
#define TTABLE_H_

enum ALPHAS {ALPHA_0_05, ALPHA_0_005, ALPHA_0_00625, ALPHA_0_001, ALPHA_0_0125, ALPHA_0_025};

namespace ttable {

extern const int minor_count;
extern const int boost;
extern const int df_max;

extern const double icdf[6][900];

}
#endif /* TTABLE_H_ */
